//i18n
function changeLanguage(pagename) {
    var _lang = localStorage.getItem("language");
    jQuery.i18n.properties({ // 加载资浏览器语言对应的资源文件
        name: pagename, // 资源文件名称
        path: '../i18n/', // 资源文件路径
        mode: 'both', // 用 Map 的方式使用资源文件中的值
        language: _lang,
        cache: false,
        encoding: 'UTF-8',
        callback: function() { // 加载成功后设置显示内容
            $("[data-i18n]").each(function() {
                $(this).html($.i18n.prop($(this).attr("data-i18n")));
            });
            $("input[data-place]").each(function() {
                $(this).attr("placeholder", $.i18n.prop($(this).attr("data-place")));
            });
            $("textarea[data-place]").each(function() {
                $(this).attr("placeholder", $.i18n.prop($(this).attr("data-place")));
            });
            $("input[data-val]").each(function() {
                $(this).val($.i18n.prop($(this).attr("data-val")));
            });
            $("th[data-tit]").each(function() {
                $(this).attr("title", $.i18n.prop($(this).attr("data-tit")));
            });
        }
    });
}
//datatables
var Langzh = {
    "decimal": "",
    "emptyTable": "没有数据",
    "info": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
    "infoEmpty": "显示第 0 至 0 项结果，共 0 项",
    "infoFiltered": "(从 _MAX_ 条数据中检索)",
    "infoPostFix": "",
    "thousands": ",",
    "lengthMenu": "每页显示: _MENU_ 条记录",
    "loadingRecords": "数据载入中...",
    "processing": "数据载入中...",
    "search": "查找",
    "zeroRecords": "没有数据",
    "paginate": {
        "first": "首页",
        "last": "尾页",
        "next": "后一页",
        "previous": "前一页"
    },
    "aria": {
        "sortAscending": ": 以升序排列此列",
        "sortDescending": ": 以降序排列此列"
    }
};
var dynamic_zh = {
    home_chooseTxt: "全部项目",
    home_projectitem: "项目名称",
    home_delete: "确定删除吗?",
    home_deletesuc: "删除成功",
    home_ok: "确定",
    home_cancel: "取消",
    homeCharts_title1: "页面浏览情况-访问请求总量",
    homeCharts_title2: "页面浏览情况-访问请求地理分布",
    homeCharts_title3: "页面浏览情况-TOP50 访问请求路径",
    homeCharts_title4: "页面浏览情况-TOP50 访问请求路径(占比图)",
    homeCharts_title5: "访问用户IP分析-独立IP总量",
    homeCharts_title6: "访问用户IP分析-访问请求IP地理分布",
    homeCharts_title7: "访问用户IP分析-TOP50 访问请求量的IP",
    homeCharts_title8: "访问用户IP分析-TOP50 访问请求量的IP(占比图)",
    homeCharts_title9: "访问请求数据量-访问请求数据总量",
    homeCharts_title10: "访问请求数据量-访问请求数据量地理分布",
    homeCharts_title11: "访问请求数据量-TOP50 数据量的访问请求路径",
    homeCharts_title12: "访问请求数据量-TOP50 数据量的访问请求IP",
    homeCharts_title13: "HTTP响应状态码-访问请求响应状态",
    homeCharts_title14: "HTTP响应状态码-访问请求响应状态时间分布",
    homeCharts_title15: "HTTP响应状态码-TOP50 响应状态的访问请求路径",
    homeCharts_title16: "HTTP响应状态码-TOP50 响应状态的访问请求IP来源",
    homeCharts_title17: "访问端浏览器-TOP50 访问端浏览器",
    homeCharts_title19: "访问端浏览器-TOP50 访问端浏览器(占比图)",
    homeCharts_title20: "访问端操作系统-TOP50 访问端操作系统",
    homeCharts_title21: "访问端操作系统-TOP50 访问端操作系统(占比图)",
    homeCharts_title22: "访问请求类型-TOP50 访问请求类型",
    homeCharts_title23: "访问请求类型-TOP50 访问请求类型(占比图)",
    homeCharts_title24: "页面停留时间-TOP50 停留时长的访问请求路径",
    homeCharts_title25: "页面停留时间-TOP50 停留时长的访问请求路径(占比图)",
    homeCharts_title26: "访问来源分析-TOP50 访问请求来源",
    homeCharts_title27: "访问来源分析-TOP50 访问请求来源(占比图)",
    homeCharts_title28: "网络爬虫-爬取行为总览",
    homeCharts_title29: "网络爬虫-TOP50 爬取源IP",
    homeCharts_title30: "网络爬虫-TOP50 爬取路径",
    homeCharts_title31: "网络爬虫-爬取行为响应状态",
    homeCharts_title32: "SQL注入分析-SQL注入行为总览",
    homeCharts_title33: "SQL注入分析-TOP50 SQL注入源IP",
    homeCharts_title34: "SQL注入分析-TOP50 注入路径",
    homeCharts_title35: "SQL注入分析-注入行为响应状态",
    homeCharts_title36: "文件包含漏洞分析-文件包含漏洞总览",
    homeCharts_title37: "文件包含漏洞分析-TOP50 攻击源IP",
    homeCharts_title38: "文件包含漏洞分析-TOP50 攻击路径",
    homeCharts_title39: "文件包含漏洞分析-攻击行为响应状态",
    homeCharts_title40: "跨站脚本攻击分析-跨站脚本攻击总览",
    homeCharts_title41: "跨站脚本攻击分析-TOP50 攻击源IP",
    homeCharts_title42: "跨站脚本攻击分析-TOP50 攻击路径",
    homeCharts_title43: "跨站脚本攻击分析-攻击行为响应状态",
    strings_senderror: "请求失败",
    manage_cancle: "取消",
    manage_delselected: "删除选中",
    manage_control: "操作",
    manage_analysis: "分析报表",
    manage_search: "智能搜索",
    manage_rename: "编辑名称",
    manage_redes: "编辑描述",
    manage_upload: "上传数据",
    manage_startProject: "启动项目",
    manage_delProject: "删除项目",
    manage_delData: "删除数据",
    manage_inactive: "未启用",
    manage_active: "可使用",
    manage_processing: "处理中",
    manage_type1: "文件",
    manage_type2: "流式",
    manage_newP: "新建项目",
    manage_newD: "新建项目描述",
    manage_sl_apply: "确定",
    manage_sl_pleasea: "请选择项目：",
    manage_sl_makesurea: "确定要启动项目吗",
    manage_sl_pa: "对项目下数据进行统计分析需要经历一段时间，您可以通过项目状态了解进展。",
    manage_sl_run: "确定启动",
    manage_sl_runsucess: "启动成功",
    manage_sl_writepro: "编辑项目名称",
    manage_sl_pleaseb: "请填写内容",
    manage_sl_subsucess: "提交成功",
    manage_sl_writedes: "编辑项目描述",
    manage_sl_newsuccess: "新建成功",
    manage_sl_newfalse: "新建失败",
    manage_sl_makesureb: "确定要删除项目吗",
    manage_sl_pb: "删除项目会导致项目内所有数据一并删除；删除的项目将在回收站中保存七天",
    manage_sl_suredel: "确定删除",
    manage_sl_delsuccess: "删除成功",
    manage_sl_delfalse: "删除失败",
    manage_sl_pleasec: "请先选择删除对象",
    manage_sl_makesurec: "确定要删除数据吗",
    manage_sl_pc: "数据删除后将无法恢复，请谨慎处理。删除数据会导致项目内统计数据发生变化，因此需要对项目进行重新统计分析，这需要经历一段时间，在此期间您仍可以在“分析报表”中看到原有数据信息，但无法在“智能搜索”中搜索已删除数据。",
    manage_sl_makesured: "确定要添加到该项目吗",
    manage_sl_pd: "增加数据会导致项目内统计数据发生变化，因此需要对项目进行重新统计分析，这需要经历一段时间",
    manage_sl_savasuccess: "保存成功",
    manage_sl_savefalse: "保存失败",
    manage_sl_getfalse: "获取用户信息失败",
    search_ChartsL: "搜索结果总量统计图表",
    search_ChartsR: "搜索结果地理视图",
    search_project: "项目：",
    search_keyword: "搜索词：",
    search_time: "时间范围：",
    search_sl_pleasew: "请输入您要搜索的内容",
    search_sl_feat: "搜索结果已存在，请勿重复搜索",
    search_charts_ask: "访问次数",
    search_charts_time_: "时间",
    search_charts_a: "切换为面积图",
    search_charts_b: "切换为折线图",
    search_charts_c: "切换为柱形图",
    search_charts_d: "切换为散点图",
    search_charts_save: "保存为图片",
    search_ok: "确定",
    search_select: "请选择项目",
    recycle_a1: "还原成功",
    recycle_a2: "确定",
    recycle_a3: "取消",
    recycle_a4: "确定要删除项目吗",
    recycle_a5: "彻底删除后，该项目及项目内所有数据将无法恢复，请谨慎处理",
    recycle_a6: "请先选择还原对象",
    recycle_a7: "请先选择删除对象",
    recycle_a8: "确定删除",
    recycle_a9: "删除成功",
    recycle_a10: "删除失败",
    recycle_a11: "还原失败",
    check_check: "请先选择账单",
    check_detail: "查看明细",
    check_send: "已发送",
    check_back: "您选择的帐期明细已发送到您的邮箱，请注意查收！",
    package_value1: ["", "3GB/月", "10GB/月", "20GB/月", "50GB/月", "100GB/月", "200GB/月", "300GB/月", "400GB/月", "500GB/月"],
    package_value2: ["", "6个月", "12个月"],
    package_value3: ["", "30天", "90天", "180天", "365天"],
    package_sum: "19,800.00元",
    package_tell: "通知成功",
    package_hours: "您的专属销售服务人员会在48小时内与您沟通，请保持电话畅通",
    package_sure: "已确认",
    package_create: "您的订单已创建，开数科技将在48小时内安排您的专属销售服务人员与您签署服务合同，请保持您的电话畅通",
    package_yuan: "元",
    uploadParse_saveAnalysis:"确认解析格式?",
    uploadParse_saveAnalysisexp:"确认解析格式后，将启动分析处理流程，这可能会花费一定的时间，处理后您将无法变更数据的项目归属。如您认为解析格式有误，请联系开数科技技术支持获取帮助（E-mail: support@open01.com，或请拨打电话:010-8272 4800）。",
    upload_proRepetition:"项目名称重复",
    upload_proNameEmpty:"请填写项目名称",
    upload_ok: "确定",
    upload_confirm: "确定操作",
    upload_cancel: "取消",
    upload_save: "保存?",
    upload_saveexp: "选择“保存”意味着您确认解析格式，但不启动分析处理流程。您之后可以在“资源管理”界面启动处理或变更数据的项目归属",
    upload_saveAnalysis: "保存并分析?",
    upload_saveAnalysisexp: "选择“保存并分析”意味着您确认解析格式，并即刻启动分析处理流程。这可能会花费一定的时间，处理后您将无法变更数据的项目归属。",
    upload_saveAnalysistips: "正在保存,请稍候...",
    upload_skipStep: "请选择所属项目",
    upload_streamCreatProject: "请先创建一个项目",
    upload_Attachment: "浏览器上传",
    upload_StreamingData: "流式上传",
    upload_Streamingtxt1: "流式上传预解析",
    upload_fileName: "文件名",
    upload_fileType: "文件类型",
    upload_fileSize: "文件大小",
    upload_upLoadtitle1: "正在上传...",
    upload_upLoadFormtips1: "请上传正确的格式",
    upload_upLoadFormtips2: "除正常日志格式外,可上传的压缩文件格式：    .tar.gzip、.zip、.tar.xz、.xz,.rar、.tar、.tar.gz、.gz、.bz2、.tar.bz2、.z、.tar.z ；",
    upload_submitBtntips0: "请先选择或创建一个项目后进行上传。",
    upload_submitBtntips1: "请首先选择需要上传的文件!",
    upload_submitBtntips2: "数据上传需要花费一定的时间，请不要关闭浏览器或跳转其他页面，否则无法确认解析结果!",
    upload_submitBtntips3: "数据上传超量",
    upload_submitBtntips4: "本账期内上传数据已超量，您可以：",
    upload_submitBtntips5: "超量计费并上传",
    upload_submitBtntips6: "暂不上传",
    upload_submitBtntips7: "超额上传的数据费用为：50元/Gb/日。数据有效存储期与套餐内数据一致。",
    upload_submitBtntips8: "确定上传",
    upload_submitBtntips9: "账户余额不足",
    upload_submitBtntips10: "账户余额不足。无法再次上传数据。",
    upload_submitBtntips11: "标签已存在请重新输入!",
    upload_submitBtntips16: "项目不能为空！",
    upload_submitBtntips12: "日志的绝对路径不能为空！",
    upload_submitBtntips13: "日志的日志类型不能为空！",
    upload_submitBtntips14: "操作成功",
    upload_submitBtntips15: "数据上传需要花费一定的时间，请不要关闭浏览器或跳转其他页面!",
    upload_isExcessData1:"本账期内上传的数据量已超过80%，请您合理安排数据上传量，或升级套餐。如需获取帮助，请联系朗录商务支持（电话：010 8272 4800;邮箱：support@open01.com）",
    upload_isExcessData2:"本账期内上传数据已超量，超额上传的数据费用为：",
    upload_isExcessData3:"。数据有效存储期与套餐内数据一致。如需获取帮助，请联系朗录商务支持（电话：010 8272 4800;邮箱：support@open01.com）",
    upload_isExcessData4:"您的账户余额不足。请及时续费以免影响使用。如您已经成功续费，请忽略此信息。如需获取帮助，请联系朗录商务支持（电话：010 8272 4800;邮箱：support@open01.com）",
    upload_isExcessData5:"余额不足",
    upload_isExcessData6:"48小时内充值",
    upload_n_name: "新建项目",
    upload_n_des: "新建项目描述",
    upload_n_setupprojectsuc: "新建项目成功",
    upload_copySuccess: "复制成功！",
    upload_up: "上传",
    analysis_emptyproject: "项目列表为空",
    analysis_form:"自",
    analysis_to:"至",
    analysis_errorimg: "img/error.png",
    analysis_tools1: "切换为折线面积图",
    analysis_tools2: "切换为折线图",
    analysis_tools3: "切换为柱形图",
    analysis_tools4: "切换为散点图",
    analysis_tools5: "返回原图表",
    analysis_tools6: "保存为图片",
    analysis_tools7: "还原",
    analysis_tools8: "关闭扩展图表",
    analysis_percent: "占比",
    analysis_Times: "次",
    analysis_viewData: "数据明细",
    analysis_viewChart: '查看图表',
    analysis_ok: "确认",
    analysis_cancel: "取消",
    analysis_step: "序号",
    analysis_TimeStrp: "时间",
    analysis_logTime: "日志时间",
    analysis_sourceIp: "来源IP",
    analysis_responseStatus: "响应状态",
    analysis_Addres: "地理位置",
    analysis_pageViewNum: "页面访问量（次）",
    analysis_DataNum: "数据流量",
    analysis_IpNum: "独立IP数(个)",
    analysis_IpRanking: "独立IP数排名",
    analysis_ViewIP: "IP访问次数",
    analysis_ViewNum: "访问次数(次)",
    analysis_viewRanking: "访问量排名",
    analysis_Timeonpath: "页面停留时间(秒)",
    analysis_TimeonpathRank: "页面停留时间排行",
    analysis_TrafficS: "访问来源",
    analysis_DataTraffic: "数据流量",
    analysis_dataRanking: "数据传输量排名",
    analysis_cvr: "转化率",
    analysis_os: "系统类型",
    analysis_br: "浏览器类型",
    analysis_status: "状态码",
    analysis_Frequency: "该状态出现次数",
    analysis_FrequencyNum: "出现次数(次)",
    analysis_emptyProSelect: "DEMO",
    analysis_atOnceSetup:"立即开通",
    analysis_setupMessage:"通知成功,您的专属服务人员会在24小时内与您沟通,请保持电话畅通.",
    analysis_seesionExpired: "Session已过期，请重新登录！",
    analysis_RequestDataTransfer: "请求数据量",
    analysis_Requesttype: "页面请求类型",
    analysis_Requesttype2: "请求类型",
    analysis_RequsetFrequency: "请求次数",
    analysis_addDashboardsuc: "添加成功",
    analysis_addDashboarddef: "添加首页失败",
    analysis_addDashboarderr1: "首页中已存在此图表,请勿重复添加",
    analysis_addDashboarderr2: "当前项目为空，无法添加到首页",
    analysis_addDashboard: "确认将此图表添加到首页?",
    analysis_addDashboardexp: "添加到首页后您将在首页中看到此图表的实时预览图，点击预览图快速跳转到该图表的分析页面。",
    analysis_daterangeArr: ['今日', '昨日', '本周', '本月', '本年'],
    analysis_pv_paginationArr: ['访问请求总量', '访问请求地理分布', 'TOP50 访问请求路径', 'TOP50 访问请求路径(占比图)'],
    analysis_PageView: '访问次数(次)',
    analysis_UniqueIP: "独立IP数(个)",
    analysis_br_paginationArr: ['TOP50 访问端浏览器', 'TOP50 访问端浏览器(占比图)'],
    analysis_br_others: "其他",
    analysis_cvr_othersOs:"未记录操作系统信息",
    analysis_cvr_othersBr:"未记录浏览器信息",
    analysis_cvr_paginationArr: ['自定义转化率分析'],
    analysis_cvr_steps: "步骤",
    analysis_cvr_text0: "当前项目列表为空，请选择一个项目或创建一个项目后操作。",
    analysis_cvr_text1: "相对上一步转化率",
    analysis_cvr_text2: "相对总转化率",
    analysis_cvr_text3:"请完整填写数据,或移除不需要的流程.",
    analysis_cvr_placeholder1: "请输入URL的描述",
    analysis_cvr_placeholder2: "请输入想要分析的URL",
    analysis_data_paginationArr: ['访问请求数据总量', '访问请求数据量地理分布', 'TOP50 数据量的访问请求路径', 'TOP50 数据量的访问请求IP'],
    analysis_ip_paginationArr: ['独立IP总量', '访问请求IP地理分布', 'TOP50 访问请求量的IP', 'TOP50 访问请求量的IP(占比图)'],
    analysis_os_paginationArr: ['TOP50 访问端操作系统', 'TOP50 访问端操作系统(占比图)'],
    analysis_request_paginationArr: ['TOP50 访问请求类型', 'TOP50 访问请求类型(占比图)'],
    analysis_rf_paginationArr: ['TOP50 访问请求来源', 'TOP50 访问请求来源(占比图)'],
    analysis_status_paginationArr: ['访问请求响应状态', '访问请求响应状态时间分布', 'TOP50 响应状态的访问请求路径', 'TOP50 响应状态的访问请求IP来源'],
    analysis_status_RankingURL: "产生该状态的URL排名",
    analysis_status_RankingIP: "产生该状态的IP排名",
    analysis_tp_paginationArr: [ 'TOP50 停留时长的访问请求路径', 'TOP50 停留时长的访问请求路径(占比图)'],
    analysis_tp_secTimes: "秒/次",
    analysis_tp_secIp: "秒/IP",
    analysis_crawler_paginationArr:['爬取行为总览', 'TOP50 爬取源IP', 'TOP50 爬取路径', '爬取行为响应状态'],
    analysis_crawler_crawlerNum:"爬虫访问量（次）",
    analysis_crawler_CrawlerPvPercent:"爬虫访问占比（%）",
    analysis_crawler_notCrawler:"非爬虫访问量（次）",
    analysis_crawler_unCrawlerPvPercent:"非爬虫访问占比（%）",
    analysis_crawler_CrawlerIp:"爬取源IP",
    analysis_crawler_CrawlerURL:"爬取路径URL",
    analysis_crawler_PvNum:"总访问次数（次）",
    analysis_crawler_status1:"爬取成功次数(2XX)",
    analysis_crawler_status1_1:"爬取成功次数(次)",
    analysis_crawler_crawlerSucPercent:"爬取成功占比（%）",
    analysis_crawler_status2:"爬取重定向次数(3XX)",
    analysis_crawler_status2_1:"爬取重定向次数(次)",
    analysis_crawler_crawlerRedPercent:"爬取重定向占比（%）",
    analysis_crawler_status3:"爬取失败次数(4XX,5XX)",
    analysis_crawler_status3_1:"爬取失败次数(次)",
    analysis_crawler_crawlerFailPercent:"爬取失败占比（%）",
    analysis_crawler_statusNum:"合计爬虫访问量(次)",
    analysis_sql_paginationArr:['SQL注入行为总览', 'TOP50 SQL注入源IP', 'TOP50 注入路径', '注入行为响应状态'],
    analysis_sql_attackNum:"攻击行为次数（次）",
    analysis_sql_sqlIp:"注入源IP",
    analysis_sql_sqlURL:"注入路径URL",
    analysis_sql_attackRanking:"攻击量排名",
    analysis_sql_attackStatus1:"攻击成功次数(2XX)",
    analysis_sql_attackStatus1_1:"攻击成功次数(次)",
    analysis_attackSucPercent:"攻击成功占比（%）",
    analysis_sql_attackStatus2:"攻击重定向次数(3XX)",
    analysis_sql_attackStatus2_1:"攻击重定向次数(次)",
    analysis_attackRedPercent:"攻击重定向占比（%）",
    analysis_sql_attackStatus3:"攻击不成功次数(4XX,5XX)",
    analysis_sql_attackStatus3_1:"攻击不成功次数(次)",
    analysis_attackFailPercent:"攻击失败占比（%）",
    analysis_sql_attackStatusNum:"合计攻击访问量（次）",
    analysis_sql_attackStatusTimes:"状态出现次数（次）",
    analysis_fi_paginationArr:['文件包含漏洞总览', 'TOP50 攻击源IP', 'TOP50 攻击路径', '攻击行为响应状态'],
    analysis_fi_attackNum:"攻击行为次数（次）",
    analysis_fi_attackRanking:"攻击量排名",
    analysis_fi_attackStatus1:"攻击成功次数(2XX)",
    analysis_fi_attackStatus1_1:"攻击成功次数(次)",
    analysis_fi_attackStatus2:"攻击重定向次数(3XX)",
    analysis_fi_attackStatus2_1:"攻击重定向次数(次)",
    analysis_fi_attackStatus3:"攻击不成功次数(4XX,5XX)",
    analysis_fi_attackStatus3_1:"攻击不成功次数(次)",
    analysis_fi_attackStatusNum:"合计攻击访问量（次）",
    analysis_fi_attackStatusTimes:"状态出现次数（次）",
    analysis_xss_paginationArr:['跨站脚本攻击总览', 'TOP50 攻击源IP', 'TOP50 攻击路径', '攻击行为响应状态'],
    analysis_xss_attackNum:"攻击行为次数（次）",
    analysis_xss_attackRanking:"攻击量排名",
    analysis_xss_attackStatus1:"攻击成功次数(2XX)",
    analysis_xss_attackStatus1_1:"攻击成功次数(次)",
    analysis_xss_attackStatus2:"攻击重定向次数(3XX)",
    analysis_xss_attackStatus2_1:"攻击重定向次数(次)",
    analysis_xss_attackStatus3:"攻击不成功次数(4XX,5XX)",
    analysis_xss_attackStatus3_1:"攻击不成功次数(次)",
    analysis_xss_attackStatusNum:"合计攻击访问量（次）",
    analysis_xss_attackStatusTimes:"状态出现次数（次）",
    option_passwordErr1: "您输入的密码有误，请重新输入！",
    option_passwordErr2: "两次输入密码不一致，请重新输入！",
    option_passwordErr3: "两次输入密码不能为空，请重新输入！",
    option_passwordSuc: "修改成功,请重新登陆！",
    option_canotempty: "所有数据不能为空，请检查！",
    option_ok: "确认",
    option_avatarsuc: "保存头像成功",
    option_avatarfaild: "保存头像失败",
    option_savesuc: "保存成功",
    option_savefaild: "保存失败",
    option_emailerr: "邮箱格式有误，请重新填写",
    option_phoneerr: "手机号码有误，请重填！",
    notice_open: "开启",
    notice_close: "关闭",
    notice_readed: "已读",
    notice_unread: "未读",
    notice_options_UpgradePackage: "升级套餐",
    notice_downloadCSV: "下载CSV文件",
    notice_nomessages: "暂无消息",
    emonitor_t_s:"分钟",
    emonitor_t_h:"小时",
    emonitor_t_d:"天",
    emonitor_t_w:"周",
    emonitor_detail:"查看详情",
    emonitor_godetail:"历史趋势",
    emonitor_cont:"监控内容",
    emonitor_project:"监控项目",
    emonitor_frequency:"监控频率",
    emonitor_range:"监控范围",
    emonitor_create:"创建日期",
    emonitor_span:"次",
    emonitor_yside:"统计值（次）",
    emonitor_fre:"频率",
    ehome_yemail:"开启通知",
    ehome_nemail:"关闭通知",
    ehome_yemailA:"已为您开启该监控任务的邮件提醒功能。",
    ehome_nemailA:"已为您关闭该监控任务的邮件提醒功能。",
};
var dynamic_en = {
    home_chooseTxt: "All",
    home_projectitem: "Project Item",
    home_delete: "Are you sure to remove this chart?",
    home_deletesuc: "Removed successfully!",
    home_deletefaild: "Removed faild.",
    home_ok: "OK",
    home_cancel: "Cancel",
    homeCharts_title1: "Page/Path View - Overview",
    homeCharts_title2: "Page/Path View - Distribution",
    homeCharts_title3: "Page/Path View - Ranking",
    homeCharts_title4: "Page/Path View - Proportion",
    homeCharts_title5: "Unique IP - Overview",
    homeCharts_title6: "Unique IP - Distribution",
    homeCharts_title7: "Unique IP - Ranking",
    homeCharts_title8: "Unique IP - Proportion",
    homeCharts_title9: "Data Transfer - Overview",
    homeCharts_title10: "Data Transfer - Distribution",
    homeCharts_title11: "Data Transfer - Ranking on Page (Path)",
    homeCharts_title12: "Data Transfer - Ranking on IP",
    homeCharts_title13: "Http Code - Overview",
    homeCharts_title14: "Http Code - Frequency",
    homeCharts_title15: "Http Code - Ranking on Page/Path",
    homeCharts_title16: "Http Code - Ranking on IP",
    homeCharts_title17: "Browser - Proportion",
    homeCharts_title19: "Browser - Ranking",
    homeCharts_title20: "Operating System - Proportion",
    homeCharts_title21: "Operating System - Ranking",
    homeCharts_title22: "Request Type - Proportion",
    homeCharts_title23: "Request Type - Ranking",
    homeCharts_title24: "Time on Page/Path - Ranking",
    homeCharts_title25: "Time on Page/Path - Proportion",
    homeCharts_title26: "Traffic Sources - Proportion",
    homeCharts_title27: "Traffic Sources - Ranking",
    homeCharts_title28: "Web Crawler - Overview",
    homeCharts_title29: "Web Crawler - Ranking on IP",
    homeCharts_title30: "Web Crawler - Ranking on Path",
    homeCharts_title31: "Web Crawler - Success or Failure",
    homeCharts_title32: "SQL Insert - Overview",
    homeCharts_title33: "SQL Insert - Ranking on IP",
    homeCharts_title34: "SQL Insert - Ranking on Path",
    homeCharts_title35: "SQL Insert - Success or Failure",
    homeCharts_title36: "File Inclusion Vulnerability - Overview",
    homeCharts_title37: "File Inclusion Vulnerability - Ranking on IP",
    homeCharts_title38: "File Inclusion Vulnerability - Ranking on Path",
    homeCharts_title39: "File Inclusion Vulnerability - Success or Failure",
    homeCharts_title40: "Cross Site Script Vulnerability - Overview",
    homeCharts_title41: "Cross Site Script Vulnerability - Ranking on IP",
    homeCharts_title42: "Cross Site Script Vulnerability - Ranking on Path",
    homeCharts_title43: "Cross Site Script Vulnerability - Success or Failure",
    strings_senderror: "Request failed ",
    manage_cancle: "Cancle",
    manage_delselected: "delete",
    manage_control: "Operation",
    manage_analysis: "Analysis Report",
    manage_search: "Log Search",
    manage_rename: "Rename",
    manage_redes: "Redescription",
    manage_upload: "Upload",
    manage_startProject: "Start analysis",
    manage_delProject: "Delete project",
    manage_delData: "Delete Data",
    manage_inactive: "Unused",
    manage_active: "Finished",
    manage_processing: "Processing",
    manage_type1: "file",
    manage_type2: "stream",
    manage_newP: "new project",
    manage_newD: "new description",
    manage_sl_apply: "OK",
    manage_sl_pleasea: "Please select a project",
    manage_sl_makesurea: "Do you want to start analyzing this project",
    manage_sl_pa: "It will take some time to analyze the data of the project, and you can find the progress from STATUS.",
    manage_sl_run: "Sure",
    manage_sl_runsucess: "Start analysis",
    manage_sl_writepro: "Title",
    manage_sl_pleaseb: "Please fill in the content",
    manage_sl_subsucess: "Submitted successfully",
    manage_sl_writedes: "Description",
    manage_sl_newsuccess: "Created successfully",
    manage_sl_newfalse: "Creation failed",
    manage_sl_makesureb: "Are you sure to delete this project?",
    manage_sl_pb: "Project deletion means all data belongs to this project will be deleted one time, are you sure to do that? Deleted project will be temporary saved in the recycle bin for 7 days.",
    manage_sl_suredel: "Sure",
    manage_sl_delsuccess: "Deleted successfully",
    manage_sl_delfalse: "Delete failed",
    manage_sl_pleasec: "Please select a object",
    manage_sl_makesurec: "Are you sure to delete this data?",
    manage_sl_pc: "Delete data will be unable to restore. After deletion, the project containing this data will be analyzed again, which will take some time, during which you may still see the original data in analysis report, but can not search it.",
    manage_sl_makesured: "Are you sure to add data to this project?",
    manage_sl_pd: "After adding data, the project will be analyzed again, which will take some time.",
    manage_sl_savasuccess: "Saved successfully",
    manage_sl_savefalse: "Save failed",
    manage_sl_getfalse: "Failed to get user information",
    search_ChartsL: "Overview",
    search_ChartsR: "Distribution",
    search_project: "Project：",
    search_keyword: "Keyword：",
    search_time: "Period：",
    search_sl_pleasew: "Please enter the text to search for",
    search_sl_feat: "The search result has already exists",
    search_charts_ask: "Frequency",
    search_charts_time_: "Time Stamp",
    search_charts_a: "Area chart",
    search_charts_b: "Line chart",
    search_charts_c: "Histogram",
    search_charts_d: "Scatter plot",
    search_charts_save: "save as .png",
    search_ok: "OK",
    search_select: "Please select a project",
    recycle_a1: "Recovered successfully",
    recycle_a2: "OK",
    recycle_a3: "Cancel",
    recycle_a4: "Are you sure to delete this project?",
    recycle_a5: "Project deletion means all data belongs to this project will be deleted one time, data deleted will be unable to restore.",
    recycle_a6: "Please select a object",
    recycle_a7: "Please select a object",
    recycle_a8: "OK",
    recycle_a9: "Delete successfully",
    recycle_a10: "Delete failed",
    recycle_a11: "Recovered failed",
    check_check: "Select your bill, please",
    check_detail: "View Details",
    check_send: "Sent successfully！",
    check_back: "CAMPASS Bill has been sent to your E-mail，please note that check.",
    package_value1: ["", "3GB/month", "10GB/month", "20GB/month", "50GB/month", "100GB/month", "200GB/month", "300GB/month", "400GB/month", "500GB/month"],
    package_value2: ["", "6months", "12months"],
    package_value3: ["", "30day", "90day", "180day", "365day"],
    package_sum: "19,800.00 RMB",
    package_tell: "Submitted Successfully",
    package_hours: "Our staff will contact you within 48 hours, please keep your phone working properly.",
    package_sure: "Submitted Successfully",
    package_create: "Upgrade information has been submitted, service contract will be confirmed with you within 48 hours, please keep your phone working properly.",
    package_yuan: " RMB",
    uploadParse_saveAnalysis:"Save & Analysis?",
    uploadParse_saveAnalysisexp:'“Save & Analysis" means you confirmed the parsing results, and start the analysis processing, which will take some time and defined the attribution of data file to this project. If the parsing format is incorrect, please contact us for technical support for ( E-mail: support@open01.com, or please call: 010-8272 4800).',
    upload_proRepetition:"Duplicate project name",
    upload_proNameEmpty:"Please enter your project name",
    upload_ok: "OK",
    upload_confirm: "OK",
    upload_cancel: "Cancel",
    upload_saveonly: "Save only?",
    upload_saveexp: '"Save only"means you confirmed the parsing results,but do not start the analysis processing.You can then start the analysis processing or change data to other project on page "Resource Management"',
    upload_saveAnalysis: "Save & Analysis?",
    upload_saveAnalysisexp: '“Save & Analysis" means you confirmed the parsing results, and start the analysis processing, which will take some time and defined the attribution of data file to this project.',
    upload_saveAnalysistips: "Saving",
    upload_skipStep: "Select project",
    upload_streamCreatProject: "Please create a project",
    upload_Attachment: "Attachment",
    upload_StreamingData: "Streaming Data",
    upload_Streamingtxt1: "Data parsing result",
    upload_fileName: "File name",
    upload_fileType: "File type",
    upload_fileSize: "File size",
    upload_upLoadtitle1: "UPLOADING...",
    upload_upLoadFormtips1: "Unsupported file format.",
    upload_upLoadFormtips2: "We accept the original log file (e.g. txt, log, json, csv, excel), or  compressed file: zip, .tar.xz, .xz, .rar, .tar, .tar.gz, .gz, .bz2, .tar.bz2, .z, .tar.z.",
    upload_submitBtntips0: "请先选择或创建一个项目后进行上传。",
    upload_submitBtntips1: "Please select  your data file.",
    upload_submitBtntips2: "Uploading will take some time, Please do not close the browser or jump to other pages.",
    upload_submitBtntips3: "The monthly data allowance has been used up.",
    upload_submitBtntips4: "The monthly data allowance has been used up, You can chose",
    upload_submitBtntips5: "Continue",
    upload_submitBtntips6: "Cancel this upload",
    upload_submitBtntips7: "The overrun data will be charged at  50 RMB/Gb/Day. Duration of data storage will be the same as the current package.",
    upload_submitBtntips8: "Continue",
    upload_submitBtntips9: "Your account balance is insufficient",
    upload_submitBtntips10: "Data upload failed, your account balance is insufficient.",
    upload_submitBtntips11: "This tag already exists, please enter a new one.",
    upload_submitBtntips16: "Please fill in the content!",
    upload_submitBtntips12: "Please fill in the content!",
    upload_submitBtntips13: "Please fill in the content!",
    upload_submitBtntips14: "Success",
    upload_submitBtntips15: "Uploading will take some time, Please do not close the browser or jump to other pages.",
    upload_isExcessData1:"80% of the monthly data allowance has been used. You may <a onclick='dataAclick()' style='font-size: 14px;text-decoration: underline;'>upgrade</a> the package to get more data analyzed.If you have topped up, please ignore the message. For any questions, please contact us  (Tel: + 86 10 82724800; E-mail: support@open01.com) for help.",
    upload_isExcessData2:"The monthly data allowance has been used up. The overrun data will be charged at ",
    upload_isExcessData3:". If you have topped up, please ignore the message. For any questions, please contact us  (Tel: + 86 10 82724800; E-mail: support@open01.com) for help.",
    upload_isExcessData4:"Your account balance is insufficient. Please top up. If you have topped up, please ignore the message. For any questions, please contact us  (Tel: + 86 10 82724800; E-mail: support@open01.com) for help.",
    upload_isExcessData5:"Your account balance is insufficient. ",
    upload_isExcessData6:"Top up in 48hrs",
    upload_n_name: "Set Up a Project",
    upload_n_des: "Description",
    upload_n_setupprojectsuc: "Created successfully",
    upload_copySuccess:　"Copy Successfully!",
    upload_up: "Upload",
    analysis_emptyproject: "Empty",
    analysis_form:"From",
    analysis_to:"To",
    analysis_errorimg: "img/error-en.png",
    analysis_tools1: "Area chart",
    analysis_tools2: "Line chart",
    analysis_tools3: "Histogram",
    analysis_tools4: "Scatter plot",
    analysis_tools5: "Go back",
    analysis_tools6: "save as .png",
    analysis_tools7: "restore",
    analysis_tools8: "Close",
    analysis_percent: "percent",
    analysis_Times: "times",
    analysis_viewData: "View Data",
    analysis_viewChart: 'View Chart',
    analysis_ok: "OK",
    analysis_cancel: "Cancel",
    analysis_step: "No.",
    analysis_TimeStrp: "Time Stamp",
    analysis_logTime: "Log time",
    analysis_sourceIp: "Source Ip",
    analysis_responseStatus: "Response Status",
    analysis_Addres: "Distribution",
    analysis_pageViewNum: "Page / Path View",
    analysis_DataNum: "Data Traffic",
    analysis_IpNum: "Unique IP",
    analysis_IpRanking: "Ranking",
    analysis_ViewIP: "View per IP",
    analysis_ViewNum: "Page / Path View",
    analysis_viewRanking: "Ranking",
    analysis_Timeonpath: "Time on page / path（s）",
    analysis_TimeonpathRank: "Ranking",
    analysis_TrafficS: "Traffic Sources",
    analysis_DataTraffic: "Data Traffic",
    analysis_dataRanking: "Ranking",
    analysis_cvr: "Goals",
    analysis_os: "Operating System",
    analysis_br: "Browser type",
    analysis_status: "Http Code",
    analysis_Frequency: "Frequency",
    analysis_FrequencyNum: "Frequency",
    analysis_emptyProSelect: "DEMO",
    analysis_atOnceSetup:"Learn More",
    analysis_setupMessage:"Submitted Successfully! Our staff will contact you within 48 hours, please keep your phone working properly.",
    analysis_seesionExpired: "Session expired, please relogin!",
    analysis_Requesttype: "Request type",
    analysis_Requesttype2: "Request type",
    analysis_RequsetFrequency: "Frequency",
    analysis_addDashboard: "Add to dashboard?",
    analysis_addDashboardexp: "You can view this chart in the dashboard.",
    analysis_addDashboardsuc: "Add to dashboard successfully.",
    analysis_addDashboarddef: "Add to dashboard failed",
    analysis_addDashboarderr1: "This chart already exists in the dashboard.",
    analysis_addDashboarderr2: "There is no data in the project and cannot be added to the dashboard.",
    analysis_daterangeArr: ['Today', 'Yesterday', 'This Week', 'This Month', 'This Year'],
    analysis_pv_paginationArr: ['Overview', 'Distribution', 'Ranking', 'Proportion'],
    analysis_PageView: 'Page / Path View',
    analysis_UniqueIP: 'Unique IP',
    analysis_br_paginationArr: ['Ranking', 'Proportion'],
    analysis_br_others: "others",
    analysis_cvr_othersOs:"others",
    analysis_cvr_othersBr:"others",
    analysis_cvr_paginationArr: ['View in the Dimension of：'],
    analysis_cvr_steps: "Step",
    analysis_cvr_text0: "No project currently, please create a project and upload your data first.",
    analysis_cvr_text1:"Conversion Rate by steps",
	analysis_cvr_text2:"Conversion Rate in total",
	analysis_cvr_text3:"Please complete the data, or remove unnecessary processes.",
	analysis_cvr_placeholder1:"Please fill in the Description",
	analysis_cvr_placeholder2:"Please fill in the URL",
    analysis_data_paginationArr: ['Overview', 'Distribution', 'Ranking on Page (Path)', 'Ranking on IP'],
    analysis_ip_paginationArr: ['Overview', 'Distribution', 'Ranking', 'Proportion'],
    analysis_os_paginationArr: ['Ranking', 'Proportion'],
    analysis_request_paginationArr: ['Ranking', 'Proportion'],
    analysis_rf_paginationArr: ['Ranking', 'Proportion'],
    analysis_status_paginationArr: ['Overview', 'Frequency', 'Ranking on Page / Path', 'Ranking on IP'],
    analysis_status_RankingURL: "Ranking on URL source",
    analysis_status_RankingIP: "Ranking on IP source",
    analysis_tp_paginationArr: ['Ranking', 'Proportion'],
    analysis_tp_secTimes: "s/times",
    analysis_tp_secIp: "s/IP",
    analysis_crawler_paginationArr:['Overview', 'Ranking on IP', 'Ranking on Path', 'Success or failure'],
    analysis_crawler_crawlerNum:"Crawling View",
    analysis_crawler_CrawlerPvPercent:"Proportion",
    analysis_crawler_notCrawler:"After Filtration",
    analysis_crawler_unCrawlerPvPercent:"Proportion",
    analysis_crawler_CrawlerIp:"Crawlers’ IP",
    analysis_crawler_CrawlerURL:"Crawling URL",
    analysis_crawler_PvNum:"Total Page/Path View",
    analysis_crawler_status1:"Crawled Successful",
    analysis_crawler_status1_1:"Crawled Successful",
    analysis_crawler_crawlerSucPercent:"Proportion",
    analysis_crawler_status2:"Redirect-Crawled",
    analysis_crawler_status2_1:"Redirect-Crawled",
    analysis_crawler_crawlerRedPercent:"Proportion",
    analysis_crawler_status3:"Crawled failed",
    analysis_crawler_status3_1:"Crawled failed",
    analysis_crawler_crawlerFailPercent:"Proportion",
    analysis_crawler_statusNum:"Total Crawling View",
    analysis_sql_paginationArr:['Overview', 'Ranking on IP', 'Ranking on Path', 'Success or failure'],
    analysis_sql_attackNum:"SQL insert",
    analysis_sql_sqlIp:"Attackers’ IP",
    analysis_sql_sqlURL:"Attacking URL",
    analysis_sql_attackRanking:"Ranking",
    analysis_sql_attackStatus1:"Attacked Successful",
    analysis_sql_attackStatus1_1:"Attacked Successful",
    analysis_attackSucPercent:"Proportion",
    analysis_sql_attackStatus2:"Redirect Attacked",
    analysis_sql_attackStatus2_1:"Redirect Attacked",
    analysis_attackRedPercent:"Proportion",
    analysis_sql_attackStatus3:"Attacked Failed",
    analysis_sql_attackStatus3_1:"Attacked Failed",
    analysis_attackFailPercent:"Proportion",
    analysis_sql_attackStatusNum:"Total SQL insert",
    analysis_sql_attackStatusTimes:"Frequency",
    analysis_fi_paginationArr:['Overview', 'Ranking on IP', 'Ranking on Path', 'Success or failure'],
    analysis_fi_attackNum:"File Inclusion Vulnerability",
    analysis_fi_attackRanking:"Ranking",
    analysis_fi_attackStatus1:"Attacked Successful",
    analysis_fi_attackStatus1_1:"Attacked Successful",
    analysis_fi_attackStatus2:"Redirect_Attacked",
    analysis_fi_attackStatus2_1:"Redirect_Attacked",
    analysis_fi_attackStatus3:"Attacked Failed",
    analysis_fi_attackStatus3_1:"Attacked Failed",
    analysis_fi_attackStatusNum:"Total File Inclusion",
    analysis_fi_attackStatusTimes:"Frequency",
    analysis_xss_paginationArr:['Overview', 'Ranking on IP', 'Ranking on Path', 'Success or failure'],
    analysis_xss_attackNum:"Cross Site Script Vulnerabilit",
    analysis_xss_attackRanking:"Ranking",
    analysis_xss_attackStatus1:"Attacked Successful",
    analysis_xss_attackStatus1_1:"Attacked Successful",
    analysis_xss_attackStatus2:"Redirect_Attacked",
    analysis_xss_attackStatus2_1:"Redirect_Attacked",
    analysis_xss_attackStatus3:"Attacked Failed",
    analysis_xss_attackStatus3_1:"Attacked Failed",
    analysis_xss_attackStatusNum:"Total Cross Site Script",
    analysis_xss_attackStatusTimes:"Frequency",
    option_passwordErr1: "Password error! please watch for to distinguish analyse the size to write",
    option_passwordErr2: "The new and confirmed passwords do not match. Please type them again.",
    option_passwordErr3: "Please fill in the content.",
    option_passwordSuc: "Your password has been revised successfully，please login again!",
    option_canotempty: "Please fill in the content",
    option_ok: "OK",
    option_avatarsuc: "Saved successfully",
    option_avatarfaild: "Save failed",
    option_savesuc: "Saved successfully",
    option_savefaild: "Save failed",
    option_emailerr: "The format is incorrect, please check the content.",
    option_phoneerr: "The format is incorrect, please check the content.",
    notice_open: "Open",
    notice_close: "Close",
    notice_readed: "Readed",
    notice_unread: "Unread",
    notice_options_UpgradePackage: "Upgrade Package",
    notice_downloadCSV: "Download CSV",
    notice_nomessages: "No messages",
    emonitor_t_s:"minute(s)",
    emonitor_t_h:"hour(s)",
    emonitor_t_d:"day(s)",
    emonitor_t_w:"week(s)",
    emonitor_detail:"Details",
    emonitor_godetail:"Historical Data",
    emonitor_cont:"Monitoring content",
    emonitor_project:"Monitoring project",
    emonitor_frequency:"Monitoring frequency",
    emonitor_range:"Monitoring time range",
    emonitor_create:"Creation Date",
    emonitor_span:"",
    emonitor_yside:"Frequency",
    emonitor_fre:"freq",
    ehome_yemail:"Turn on",
    ehome_nemail:"Turn off",
    ehome_yemailA:"The email alerts for the monitoring task have been turned on.",
    ehome_nemailA:"The email alerts for the monitoring task have been turned off.",
};
var Lang, Dynamic;
var go_zh = function() {
    Lang = Langzh;
    Dynamic = dynamic_zh;
};
var go_en = function() {
    Lang = {};
    Dynamic = dynamic_en;
};
localStorage.getItem("language") == "zh" ? go_zh() : go_en();
